InternetShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from InternetShop import settings
from auth_user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include("catalog.urls")),

    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('', include('news.urls')),
    path('deliveries/', include('Delivery.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', NewsListView.as_view(), name='home'),
    path('post/<int:pk>/', NewsDetailView.as_view(), name='post_detail'),
    path('post/new/', NewsCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', NewsDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/',NewsUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', NewsDeleteView.as_view(), name='post_delete'),
]

catalog/models.py
from django.db import models

class Phone(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    provider = models.ForeignKey('Company', on_delete=models.PROTECT, null=True)
    model = models.CharField(max_length=150, verbose_name='Модель')
    # description = models.TextField(blank=True, null=True, verbose_name='Описание')

    count_data = models.CharField(blank=True, null=True, verbose_name='Количество памяти')
    color = models.CharField(max_length=20, verbose_name='Цвет')
    processor = models.CharField(blank=True, null=True, verbose_name='Процессор')
    camera = models.CharField(blank=True, null=True, verbose_name='Камера')
    battery = models.CharField(blank=True, null=True, verbose_name='Аккумулятор')

    price = models.FloatField(verbose_name='Цена')
    photo = models.ImageField(upload_to='images/', null=True, verbose_name='Фото')

    def __str__(self):
        return f"{self.title} ({self.model})"
    class Meta:
        verbose_name = 'Телефон'
        verbose_name_plural = 'Телефоны'

class Company(models.Model):
    title = models.CharField(max_length=150, verbose_name='Company', db_index=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

templates/inc/_footer.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 70vh; /* 100% высоты окна браузера */
        }

        .content {
            flex: 1; /* Растягивает содержимое до доступного места */
        }

        .footer {
            background-color: #f8f9fa;
            padding: 20px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
            
            
        </div>
        
        <div class="footer">
            <div class="container">
                <footer class="py-3 my-4">
                    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                        <li class="nav-item"><a href="{% url 'home_index' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
                        <li class="nav-item"><a href="{% url 'phone_list' %}" class="nav-link px-2 text-body-secondary">Catalog</a></li>
                    </ul>
                    <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
                </footer>
            </div>
        </div>
    </div>
</body>
</html>

templates/inc/_header.html
<div class="container ">
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
{#        <span class="fs-4"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Простой заголовок</font></font></span>#}
    </a>
    
    <ul class="nav nav-pills">
        <a href="{% url 'home_index' %}" class="btn btn-success nav-link px-2 " style="margin-right: 10px;">На главную</a>
        <a href="{% url 'phone_list'  %}" class="nav-link px-2 btn btn-outline-info" style="margin-left: 10px;">Каталоr</a>
        
        <li ><a class="nav-link px-2 text-body-secondary " style="margin-right: 10px;">Добавить:</a></li>

        <div class="btn-group" role="group" aria-label="Basic outlined example" style="margin-right: 10px;" >
            <button type="button" class="btn btn-outline-primary">Телефон<a href="{% url 'add_phone' %}" class="nav-link px-2 text-body-secondary"></a></button>
            <button type="button" class="btn btn-outline-primary">Новость<a href="{% url 'post_new' %}" class="nav-link px-2 text-body-secondary"></a></button>
{#            <button type="button" class="btn btn-outline-primary">Поставщика<a href="{% url 'provider_new' %}" class="nav-link px-2 text-body-secondary"></a></button>#}
            <button type="button" class="btn btn-outline-primary ">Оформить заказ<a href="{% url 'deliveries_new' %}" class="nav-link px-2 text-body-secondary"></a></button>
        </div>

{#        <li ><a href="{% url 'CurentProvider_new' %}" class="nav-link px-2 text-body-secondary">Добавить заказ</a></li>#}

        {% if user.is_authenticated %}
            <a  href="{% url 'profile' %}" class="nav-item nav-link btn btn-info btn-sm mr-1" style="margin-right: 10px; margin-left: 10px;">Профиль</a>
            <a  href="{% url 'logout' %}"  class="nav-item nav-link btn btn-outline-secondary btn-sm mr-1" style="margin-left: 10px;">Выход</a>
        {% else %}
            <a href="{% url 'login'    %}" class =" btn btn-outline-primary" style="margin-right: 10px;">Вход</a>
            <a href="{% url 'register' %}" class ="nav-item nav-link btn btn-primary">Регистрация </a>
        {% endif %}

    </ul>
</header>
</div>